- templates/01_dwc_mvp/metadata.json
- templates/01_dwc_mvp/template.json
* This PR adds the discussed `template.json` to the template skeleton
* Questions to resolve before merging:
* Should the filename be `template.json`, or `01_dwc_mvp.json`?
* Should `id` be `01_dwc_mvp` or `01_dwc_mvp.xlsx` (i.e., include extension)?
* If the `id` is not the filename, should we include a `"filename": "01_dwc_mvp.xlsx"`?
* Should we include `instructions` at the moment, when none exist?
> BDR-275: Add `template.json` to the MVP DWC Template

- abis_mapping/base/types.py
* Importing types from `pandas._typing` does not work (for whatever reason, I cannot find out)
* `mypy` complains that the `types.CSVType` is of type `Union[Any, Any, Any]`
* This PR re-defines the pandas types, so they can be resolved properly
> BDR-389: Re-define `pandas` types so they can be resolved by `mypy`

- poetry.lock
- pyproject.toml
This allows projects using python `3.9` to use `abis-mapping` as a dependency
> BDR-389: Downgrade python from `^3.10` to `^3.9` for compatibility

- abis_mapping/base/types.py
- abis_mapping/templates/dwc_mvp/mapping.py
* As per title, hardcoding template to \`csv\` only for now.
* This allows for raw buffer/bytes data to be inputted, which previously could not have its format automatically determined.
* In future this handling should be better
> BDR-285: Hardcode template to `csv` only format for now

- abis_mapping/base/mapper.py
- abis_mapping/templates/dwc_mvp/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/dwc_mvp/mapping.py
- abis_mapping/utils/namespaces.py
- abis_mapping/utils/rdf.py
* Currently, mapping always uses the `example.org/` base IRI for mapping
* This PR adds *optional* argument `base_iri` to `apply_mapping()` method
* Intended usage is for user to pass `createme.org/`, `deleteme.org/`, `updateme.org/` etc. for a flexible base IRI when mapping
* This will be required down the track, and will fix issue discovered in BDR-490
> BDR-490: Allow flexible base iri to be used when mapping template

- abis_mapping/templates/dwc_mvp/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/dwc_mvp/mapping.py
* As above, removed the erroneous comma in WKT `POINT (lon lat)` generation
* Fixed example generated `ttl` as well
> BDR-476: Fix issue with WKT POINT generation (removed comma)

- abis_mapping/base/mapper.py
- abis_mapping/templates/dwc_mvp/mapping.py
- abis_mapping/templates/dwc_mvp/metadata.json
- tests/base/test_mapper.py
* Mapper implementations must now supply a `instructions_file: str` class attribute
* Mapper base class provides a `.instructions()` class method to retrieve a path to instructions file for the template
* Set `dwc_mvp.csv` instructions to its `README.md` for now
* Added unit tests
> BDR-523: Add initial instructions functionality

- abis_mapping/base/mapper.py
- abis_mapping/templates/dwc_mvp/mapping.py
* Adds `dataset_iri: Optional[rdflib.URIRef]` argument to `.apply_mapping()` interface
* This will allow us to optionally pre-generate the `tern:RDFDataset` using submission form metadata
* Otherwise, if not provided the functionality remains the same as before (default "Example" values are generated and used)
> BDR-500: Add dataset IRI argument to mapping interface

- .mypy.ini
- abis_mapping/templates/dwc_mvp/examples/margaret_river_flora/margaret_river_flora.csv
- abis_mapping/templates/dwc_mvp/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/dwc_mvp/mapping.py
- abis_mapping/utils/rdf.py
- tests/conftest.py
- tests/templates/test_dwc_mvp.py
- tests/utils/test_rdf.py
* Fixed two small bugs:
* Terminal FeatureOfInterest IRI generation was missing optional alternate `base_iri` argument
* Correctly separated the generation of `identifiedBy` and `recordedBy` provider IRIs
* Updated mapping to match the latest expected model provided in BDR-525
* Updated unit test data to match changes
* Added new `utils.rdf.toWKT()` function
* Generates `rdflib.Literal` WKT objects from a latitude and longitude
* Added unit test for the new `utils.rdf.toWKT()` function
* Fixed `mypy` falsely flagging the `tests` module with import errors
* Added new `tests.conftest.compare_graphs()` unit test helper function
* Helps compare graphs for isomorphic equality, considering different format and different systematically generated datetimes
* Updated `margaret_river_flora.csv` …
> BDR-525: More mapping updates, new utils and improved unit tests

- abis_mapping/base/mapper.py
- abis_mapping/templates/dwc_mvp/mapping.py
- abis_mapping/utils/__init__.py
- abis_mapping/utils/chunking.py
- tests/templates/test_dwc_mvp.py
- tests/utils/test_chunking.py
* Changes `ABISMapper.apply_mapping()` interface to return an `Iterator[rdflib.Graph]` instead of just `rdflib.Graph`
* Added argument `chunk_size: Optional[int]` to `ABISMapper.apply_mapping()` to specify chunk size
* Implementors are expected to provide a lazy iterator interface for mappers
* Added `utils.chunking.should_chunk()` utility function to determine when to yield a chunk
> BDR-621: Initial pass of lazy iterator chunking interface

- abis_mapping/plugins/__init__.py
- abis_mapping/plugins/coordinates.py
- abis_mapping/plugins/empty.py
- abis_mapping/plugins/mutual_inclusion.py
- abis_mapping/plugins/tabular.py
- abis_mapping/templates/occurrence_data/mapping.py
- abis_mapping/templates/occurrence_extended/mapping.py
- tests/plugins/test_coordinates.py
- tests/plugins/test_empty.py
- tests/plugins/test_mutual_inclusion.py
- tests/plugins/test_tabular.py
* Adds `plugins.mutual_inclusion` with the `MutuallyInclusive` Frictionless checker
* This checker allows the user to specify fields that _must_ be provided together
* Adds the `MutuallyInclusive` checker to `occurrence_extended.csv` for `threatStatus` and `conservationJurisdiction`
* As per Mieke in BDRC-42 / BDRC-67, these fields must be provided together or not at all
* Refactors the `plugins.checks` module to (moves checkers into their own modules):
* `plugin.coordinates` - for coordinate checking plugin
* `plugin.empty` - empty dataset checking plugin
* `plugin.tabular` - for tabular dataset checking plugin
* Adds and refactors unit tests for checking plugins
> BDRC-67: Frictionless Mutual Inclusion Plugin & Custom Checks Refactor

- abis_mapping/templates/occurrence_extended/schema.json
- abis_mapping/utils/__init__.py
- abis_mapping/utils/strings.py
- abis_mapping/utils/vocabs.py
- abis_mapping/vocabs/basis_of_record.py
- abis_mapping/vocabs/conservation_jurisdiction.py
- abis_mapping/vocabs/establishment_means.py
- abis_mapping/vocabs/identification_qualifier.py
- abis_mapping/vocabs/preparations.py
- abis_mapping/vocabs/sampling_protocol.py
- abis_mapping/vocabs/taxon_tank.py
- abis_mapping/vocabs/threat_status.py
- tests/utils/test_strings.py
* Adds alternate labels to new vocabularies
* `threatStatus` (`vocabs.threat_status`)
* `threatStatusCheckProtocol` (`vocabs.check_protocol`)
* `conservationJurisdiction` (`vocabs.conservation_jurisdiction`)
* Adds functionality to match a wider range of labels to vocabulary terms using label normalisation / sanitation.
* For example, `basisOfRecord/HumanObservation` will now match with the input values `{"Human Observation", "human-observation", "HUMAN_OBSERVATION", etc...}` in the template _without_ explicitly defining those as alternate labels
* Adds the `utils.strings.sanitise()` utility function
* Capitalises and strips all non-alphanumeric characters from a string
* This is used to normalize the vocabulary term labels
* This means vocabulary terms can be matched more broadly by only …
> BDRC-66: Vocab Improvements

- abis_mapping/templates/occurrence_data/mapping.py
- abis_mapping/templates/occurrence_data/schema.json
- abis_mapping/templates/occurrence_extended/mapping.py
- abis_mapping/templates/occurrence_extended/schema.json
- pyproject.toml
* Removed the ValidCoordinates check (check Australia mainland boundaries).
* schema.json: set latitude maximum = 0 instead -90 and longitude minimum = 0 instead of -180 in order to catch sign mistakes.
* bumped version to 2.2.0
> BDRNS-68: Remove Australia boundaries check in validation but restrict a latitude and longitude min/max values

- abis_mapping/base/mapper.py
- abis_mapping/templates/incidental_occurrence_data/examples/margaret_river_flora/margaret_river_flora_extra_cols.ttl
- abis_mapping/templates/incidental_occurrence_data/mapping.py
- abis_mapping/templates/survey_metadata/examples/minimal_extra_cols.ttl
- abis_mapping/templates/survey_metadata/mapping.py
- abis_mapping/templates/survey_occurrence_data/examples/margaret_river_flora/margaret_river_flora_extra_cols.ttl
- abis_mapping/templates/survey_occurrence_data/mapping.py
- tests/base/test_mapper.py
- tests/conftest.py
- tests/templates/test_incidental_occurrence_data.py
- tests/templates/test_survey_metadata.py
- tests/templates/test_survey_occurrence_data.py
It now adds extra fields as a json string literal to the graph for each of the three existing templates.
Some changes to note:
- Had to go back to accepting raw data into the extra schema method, as it is required in setting up the resource before iterating over its rows.
- The extra fields are now found by slicing the field_names list rather than using the difference of sets approach, to preserve field ordering
-  The extra schema method now either returns the full schema or just the difference, controlled via the full_schema flag (default: False).
> BDRSPS-177 Extra fields JSON Graph Building

- abis_mapping/plugins/wkt.py
- abis_mapping/settings.py
- abis_mapping/templates/incidental_occurrence_data/mapping.py
- abis_mapping/templates/survey_metadata/examples/minimal.ttl
- abis_mapping/templates/survey_metadata/examples/minimal_extra_cols.ttl
- abis_mapping/templates/survey_metadata/mapping.py
- abis_mapping/templates/survey_occurrence_data/mapping.py
- abis_mapping/utils/rdf.py
- tests/utils/test_rdf.py
Added spatial coverage to metadata mapping as per [BDRSPS-235](https://youtrack.gaiaresources.com.au/youtrack/issue/BDRSPS-235/ABIS-model-for-spatial-coverage-WKT).
This introduces a settings.py file to manage the shared rounding precision constant used in both the wkt plugin and rdf wkt literal utility function.
> BDRSPS-241 Add spatial coverage to survey metadata mapping

- pyproject.toml
Bumping the version to 3.0.0-a1 (alpha1) so that we can visually see if the deployment of partA is using the right version (in the swagger)
> Bumped the poetry package version to 3.0.0-a1 (alpha1)

- abis_mapping/templates/survey_metadata/examples/minimal.ttl
- abis_mapping/templates/survey_metadata/examples/minimal_extra_cols.ttl
- abis_mapping/vocabs/geodetic_datum.py
All except the WGS84 were previously set to 9.9.1. Detail found in [BDRSPS-255](https://youtrack.gaiaresources.com.au/youtrack/issue/BDRSPS-255/Double-check-geodetic-datum-URIs)
> BDRSPS-321 Updated geodetic datum uris to 0 meaning latest version

- abis_mapping/templates/survey_occurrence_data/examples/organism_qty.ttl
- abis_mapping/templates/survey_occurrence_data/mapping.py
- abis_mapping/templates/survey_site_data/examples/minimal.ttl
- abis_mapping/templates/survey_site_data/examples/minimal_extra_cols.ttl
- abis_mapping/templates/survey_site_data/mapping.py
Creates site URI consisting of dataset + `/Site/{siteID}`, both within the survey sites and occurrences. A node is then created and referenced within the field sample and sampling nodes. If no `siteID` is provided, reverts back to providing the terminal foi (Australia) per occurrence instead.
> BDRSPS-303 Implement site ID changes

- abis_mapping/templates/survey_metadata/mapping.py
The previous `NotEmpty()` check was removed and replaced with a `min_rows=1` along with `max_rows=1` arguments to the frictionless `table_dimensions()` check.
> BDRSPS-335 Made survey metadata template valid for one and only one row

- abis_mapping/base/mapper.py
- poetry.lock
- pyproject.toml
- tests/base/test_mapper.py
This change makes the additional fields extracted from a csv template all be viewed as a string.
> BDRSPS-350 Made extra fields all strings

- abis_mapping/templates/survey_site_data/mapping.py
- tests/templates/test_survey_site_data.py
The method returns a dictionary which maps `siteID` to its corresponding centroid as a point type WKT string or None of no valid point can be obtained.
> BDRSPS-374 Implemented site template centroid mapping method

- abis_mapping/templates/incidental_occurrence_data/schema.json
- abis_mapping/templates/survey_occurrence_data/schema.json
- abis_mapping/templates/survey_site_data/schema.json
- abis_mapping/vocabs/geodetic_datum.py
- tests/templates/test_survey_site_data.py
- Added AGD66 to the vocabulary for Geodetic Datum
- Added unit test to confirm validity of AGD66 
- Added AGD66 to allowable values for `geodeticDatum` column of CSV files for incidental / survey occurance data and survey site data.
> [BDRSPS-385] Added AGD66 to allowable geodeticData

- abis_mapping/utils/types.py
- tests/plugins/test_timestamp.py
- tests/utils/test_types.py
The mapping functionality was already present for the Timestamp classes just had to allow for no timezone input for the `parse_timestamp` function. 
Please approve and merge PR#105 first then if any conflicts are present please assign this PR back to me to rectify.
> BDRSPS-399 Made timestamps now allow for no timezone on template inputs

- abis_mapping/plugins/timestamp.py
- abis_mapping/templates/survey_metadata/schema.json
- tests/plugins/test_timestamp.py
To achieve this the `allowYear` and `allowYearMonth` field properties were removed, with tests updated accordingly.
> BDRSPS-396 Implement common timestamp field formats across all fields

- abis_mapping/templates/incidental_occurrence_data/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data/mapping.py
- abis_mapping/templates/survey_metadata/examples/minimal.ttl
- abis_mapping/templates/survey_metadata/examples/year.ttl
- abis_mapping/templates/survey_metadata/examples/yearmonth.ttl
- abis_mapping/templates/survey_metadata/mapping.py
- abis_mapping/templates/survey_occurrence_data/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data/examples/organism_qty.ttl
- abis_mapping/templates/survey_occurrence_data/mapping.py
- abis_mapping/templates/survey_site_data/examples/minimal.ttl
- abis_mapping/templates/survey_site_data/mapping.py
This removes all predicates `tern:resultDateTime` and `sosa:phenomenonTime` and replaces them with `time:hasTime` and nodes of type `time:Instant`. The existing `time:TemporalEntity` nodes were worked a little to have their `time:hasBeginning` and `time:hasEnd` to have objects of `time:Instant` nodes.
> BDRSPS-384 Create mapping conformity for timestamps to time:TemporalEntity

- abis_mapping/base/mapper.py
- abis_mapping/templates/incidental_occurrence_data/mapping.py
- abis_mapping/templates/incidental_occurrence_data/metadata.json
- abis_mapping/templates/survey_metadata/mapping.py
- abis_mapping/templates/survey_metadata/metadata.json
- abis_mapping/templates/survey_occurrence_data/mapping.py
- abis_mapping/templates/survey_occurrence_data/metadata.json
- abis_mapping/templates/survey_site_data/mapping.py
- abis_mapping/templates/survey_site_data/metadata.json
- tests/templates/conftest.py
- tests/templates/test_common.py
- tests/templates/test_survey_occurrence_data.py
revised template id to now be generated from metadata json. Version number now included in template id.
This is in preparation to allow for running multiple versions of templates at the same time.
> BDRSPS-435 Template IDs now include version number.

- abis_mapping/plugins/logical_or.py
- abis_mapping/templates/survey_occurrence_data/mapping.py
- abis_mapping/templates/survey_site_data/mapping.py
- tests/plugins/test_logical_or.py
- tests/templates/test_survey_occurrence_data.py
- tests/templates/test_survey_site_data.py
In the case that lat/long has been provided for all corresponding occurrences in the occurrence template of a systematic survey 3 template system. Achieved by:
- Modifying the logical OR custom check to allow for an optional input of values corresponding to a foreign key field
- Means that the validation will pass on the site template if there is at least an occurrence with the corresponding site id.
- However if the occurrence is missing lat/long AND the site is missing default geometry then it will get picked up at the occurrence template validation stage.
> BDRSPS-426 Allowing no geometry on sites

- abis_mapping/plugins/__init__.py
- abis_mapping/plugins/sites_geometry.py
- abis_mapping/templates/survey_site_data/mapping.py
- abis_mapping/templates/survey_site_data/schema.json
- tests/plugins/test_site_geometry.py
- tests/templates/test_survey_site_data.py
This implements the agreed validation rules for the site template, incorporating whether the geodetic datum is included or not. A new custom frictionless check was created for this purpose specifically, hence the hard-coding of field names within the check's `validate_row` method.
> BDRSPS-494 New site template geometry validation

- abis_mapping/templates/survey_occurrence_data/mapping.py
- abis_mapping/templates/survey_site_data/mapping.py
- tests/templates/test_survey_occurrence_data.py
- tests/templates/test_survey_site_data.py
altered siteID url creation to be url encoded for survey site and survey occurrence mappings. Added some site ids with spaces and slashes etc to show that no error raised now.
> BDRSPS-509 URL Encoding for SiteID URIRefs

- abis_mapping/base/loader.py
> BDRSPS-562: the dynamic mapping module loader now only python load modules named `mapping.py`

- abis_mapping/base/mapper.py
Wasn't being used so not required.
> BDRSPS-654 Removed get_vocab() base mapper method.

- abis_mapping/templates/incidental_occurrence_data_v2/templates/instructions.md
- abis_mapping/templates/survey_metadata/templates/instructions.md
- abis_mapping/templates/survey_occurrence_data/templates/instructions.md
- abis_mapping/templates/survey_site_data/templates/instructions.md
- docs/contexts/incidental_occurrence_data_v2.py
- docs/contexts/survey_metadata.py
- docs/contexts/survey_occurrence_data.py
- docs/contexts/survey_site_data.py
- docs/instructions.py
- docs/templates/base.md
- tests/docs/test_instructions.py
created base jinja markdown template to add version numbering to generated instruction documents and have the existing templates inherit from it.
> BDRSPS-732 Add versions to generated instructions 

- abis_mapping/base/mapper.py
- abis_mapping/templates/incidental_occurrence_data/mapping.py
- abis_mapping/templates/incidental_occurrence_data_v2/mapping.py
- abis_mapping/templates/survey_metadata/mapping.py
- abis_mapping/templates/survey_occurrence_data/mapping.py
- abis_mapping/templates/survey_site_data/mapping.py
- tests/base/test_mapper.py
- tests/plugins/test_empty.py
- tests/plugins/test_tabular.py
- tests/templates/test_common.py
Previously it was auto-detecting the encoding, which was sometimes wrong, leading to utf-8 encoded files failing to be decoded.
> BDRSPS-766 Make frictionless assume every csv input is utf-8 encoded

- .github/workflows/documentation.yml
* Install poetry before actions/setup-python - this makes actions/setup-python configure poetry to use the python version setup.
* cache poetry virtual env with cache: "poetry" option, also use --sync option to remove no-longer used packages from the cache.
* Generate markdown in own step.
* Remove cache action that did nothing.
* Build docs on PRs
> Documentation CI changes

- abis_mapping/base/mapper.py
- abis_mapping/plugins/wkt.py
- abis_mapping/settings.py
- abis_mapping/types/__init__.py
- abis_mapping/types/metadata.py
- abis_mapping/types/spatial.py
- poetry.lock
- pyproject.toml
- tests/types/test_metadata.py
- tests/types/test_spatial.py
This will enable the redirection of abis-mapping instructions when a specific versions is used in BDR-partA backend or elsewhere.
> BDRSPS-772 Defining settings using pydantic_settings model. Created metadata model.

- .gitignore
- abis_mapping/settings.py
- abis_mapping/templates/incidental_occurrence_data_v3/mapping.py
- abis_mapping/templates/survey_metadata_v2/mapping.py
- abis_mapping/templates/survey_occurrence_data_v2/mapping.py
- abis_mapping/templates/survey_site_data_v2/mapping.py
- tests/templates/conftest.py
altered condition allowing the registering of templates to be only when abis-mapping version is bumped to v5.x.x or higher.
The rationale is that it was causing unit tests to fail on BDR-partA since the returned template lists didn't match what was expected. I added a rule to exclude a yapf config i use locally since my switch back to vim.
> BDRSPS-785 Hide  new templates during tests

- abis_mapping/templates/incidental_occurrence_data/schema.json
- abis_mapping/templates/incidental_occurrence_data_v2/schema.json
- abis_mapping/templates/incidental_occurrence_data_v3/schema.json
- abis_mapping/templates/survey_occurrence_data/schema.json
- abis_mapping/templates/survey_occurrence_data_v2/mapping.py
- abis_mapping/templates/survey_occurrence_data_v2/schema.json
- abis_mapping/templates/survey_occurrence_data_v2/templates/instructions.md
- abis_mapping/vocabs/__init__.py
- abis_mapping/vocabs/conservation_authority.py
- poetry.lock
The conservation jurisdiction vocab had a name change from CONSERVATION_JURISDICTION to CONSERVATION_AUTHORITY as part of this.
> BDRSPS-780 Implemented schema.json and new mutual inclusion check for sensitivity cat and authority

- mkdocs.yml
Enabling this option: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-integration
e.g.:
> BDRSPS-823 Integrate docs TOC into nav section to free up horizontal space for tables

- abis_mapping/templates/incidental_occurrence_data_v3/templates/instructions.md
- docs/contexts/__init__.py
- docs/contexts/incidental_occurrence_data_v3.py
- docs/tables/threat_status.py
- docs/templates/base.md
- scripts/generate_instructions.sh
- tests/docs/tables/test_threat_status.py
- Modified incidental occurrence v3 instructions to match changes in template.
- Altered the threatstatus tabler to correctly display correct naming of conservationJurisdiction vs conservationAuthority field. 
- Created context for v3 incidental template instructions. 
- Added version numbering to generated mkdocs page titles to avoid confusion with duplicated titles.
> Bdrsps 870 - Incidental v3 template instructions preparations

- .gitignore
- docs/pages/archived_templates/index.md
- mkdocs.yml
> Setup directory for archiving documentation of removed templates

- abis_mapping/templates/survey_site_data_v2/examples/minimal-error-duplicate-site-ids.csv
- abis_mapping/templates/survey_site_visit_data_v2/schema.json
- abis_mapping/types/schema.py
- tests/templates/conftest.py
* fixed bug where `unique` constraints in our schema files weren't getting passed to frictionless
* added test case to site data v2 to test this
* removed dev comment from schema
* allow multiple `siteID`s in site visit template
> BDRSPS-857 Schema update for site visist data template v2

- abis_mapping/templates/incidental_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data_v3/mapping.py
* The Attribute and Attribute Value IRIs now have the value in them, instead of the row number. This greatly reduces the number we create.
* A new SampleCollection joins the Attribute node and the rows that had that attribute, remove the direct links from the rows to the Attribute nodes.
* other small changes to the Attribute and Value nodes
The following attributes are changed:
* basisOfRecord
* habitat
* preparations
* dataGeneralizations
> BDRSPS-925 Add SampleCollections for certain attributes in the incidental v3 mapping

- abis_mapping/templates/incidental_occurrence_data_v2/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_metadata/examples/minimal.ttl
- abis_mapping/templates/survey_metadata_v2/examples/minimal.ttl
- abis_mapping/templates/survey_occurrence_data/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data/examples/organism_qty.ttl
- abis_mapping/templates/survey_occurrence_data_v2/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v2/examples/organism_qty.ttl
- abis_mapping/templates/survey_site_data/examples/minimal.ttl
- abis_mapping/templates/survey_site_data_v2/examples/minimal.ttl
- abis_mapping/types/spatial.py
- poetry.lock
- pyproject.toml
- tests/templates/test_survey_site_data.py
- tests/types/test_spatial.py
The coordinates are stored internally within the `Geometry` object as long-lat up until rdf wkt literal output is to occur. The same is true for reading from a geosparql string in reverse.
> BDRSPS-872 Rectified issue of incorrect xy placement of coordinates when generating rdf wkt literals with crs defined.

- docs/tables/vocabs.py
- tests/docs/tables/test_vocabs_tabler.py
threatStatus and conservationAuthority were being rendered previously into table 2 of occurrence instructions.
> BDRSPS-932: Made it so no rows in instructions are generated when a field only contains unpublishable vocabs.

- abis_mapping/templates/survey_occurrence_data_v2/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v2/mapping.py
- abis_mapping/templates/survey_occurrence_data_v2/schema.json
BDRSPS-925 Add Collections for certain attributes in the survey occurrence v2 mapping
The Attribute and Attribute Value IRIs now have the value in them, instead of the row number.
This greatly reduces the number we create.
A new Collection node joins the Attribute node and the rows that had that attribute.
The following attributes are changed:
* basisOfRecord
* habitat
* preparations
* dataGeneralizations
Same as #272, but for the survey occurrence template
> BDRSPS-925 Add Collections for certain attributes in the survey occurrence v2 mapping

- abis_mapping/templates/incidental_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data_v3/mapping.py
Adds attribute collections for remaining attributes in the incidental v3 template:
* conservationAuthority
* identificationQualifier
* identificationRemarks
* taxonRank
These attributes are no longer linked directly to the scientific name tern:Observation and threat status tern:Observation nodes.
Instead those nodes are now members of the collections.
> BDRSPS-925 Implement collections for remaining attributes in incidental v3 mapping

- abis_mapping/templates/survey_metadata_v2/examples/minimal.ttl
- abis_mapping/templates/survey_metadata_v2/mapping.py
This will remove the creation of CREATEME iri from within the template's mapping methods. 
The attributes being assigned previously were incorrect and now use those IRIs created for `tern:Attribute` nodes.
> BDRSPS-951 Updated the mapping for attributes for the plan node of the metadata template.

- abis_mapping/templates/incidental_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data_v3/mapping.py
- abis_mapping/templates/survey_occurrence_data_v2/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v2/mapping.py
The `sensitivityCategory` attribute node is currently "floating" (not attached to anything)
This PR add a collection for it which is also floating. Once `abis:BiodiversityRecord` is implemented, the collection will be linked to that.
> BDRSPS-925 Add collection for sensitivityCategory attribute

- docs/tables/fields.py
- tests/docs/tables/test_fields.py
in an attempt to reduce the amount of conditionals being used within the Tabler, made it so serialization is primarily pushed back onto the table row objects, and the table wide concerns remain. Still a fair bit messy but  hopefully improves the situation a bit.
> BDRSPS-979 docs.tables.fields module refactored 

- abis_mapping/base/mapper.py
- abis_mapping/plugins/required.py
- abis_mapping/templates/survey_occurrence_data_v2/mapping.py
- abis_mapping/types/schema.py
- abis_mapping/types/spatial.py
- docs/tables/fields.py
- tests/types/test_schema.py
- tests/types/test_spatial.py
- tests/types/test_temporal.py
Probably the biggest change is no longer returning None when retrieving datum uris. The thought here is that previously when these were directly retrieved from within the mapping methods, that there were no protections against the vocab error that would be thrown as well as the fact that the data that is expected to hit this method is already expected to have been validated through the enum check of the `geodeticDatum` fields. A chained exception is raised in its place.
Also renamed non-uppercase comment "note" with "NOTE" to help IDEs identify better.
> BDRSPS-819 Made necessary tests or changes to types code after investigating low coverage on tests.

- .github/actions/setup-python-and-dependencies/action.yml
- .github/workflows/documentation.yml
- .github/workflows/testing.yml
Made all jobs depend on `poetry-lock` due to a test that revealed all would fail on a common issue of lockfile out of sync with pyproject.toml. Added env variables for poetry and python versions.
> BDRSPS-980 Added model documentation check to ci

- abis_mapping/templates/survey_site_data_v2/examples/minimal.ttl
- abis_mapping/templates/survey_site_data_v2/mapping.py
Previously `<http://createme.org/location/Australia>` was the terminal featureOfInterest. This was removed when we moved to abis:BiodiversityRecord and dwc:Occurrence in #305.
> BDRSPS-1014 Remove the isSampleOf predicate for sites

- abis_mapping/templates/survey_site_visit_data_v2/examples/minimal-1-row.csv
- abis_mapping/templates/survey_site_visit_data_v2/examples/minimal.csv
- abis_mapping/templates/survey_site_visit_data_v2/examples/minimal.ttl
- abis_mapping/templates/survey_site_visit_data_v2/mapping.py
- abis_mapping/templates/survey_site_visit_data_v2/schema.json
- tests/templates/conftest.py
- tests/templates/test_survey_site_visit_data_v2.py
This has flow-on effects;
* Remove OR check for ["siteVisitStart", "siteVisitEnd"]. This is redundant since siteVisitStart is always present.
* Remove cross-validation check for "siteVisitStart OR siteVisitID in occurrence template". This is redundant since siteVisitStart is always present.
> BDRSPS-1016 Make siteVisitStart field mandatory for site visit template

- abis_mapping/templates/survey_site_data/mapping.py
- abis_mapping/templates/survey_site_data_v2/mapping.py
- abis_mapping/vocabs/site_type.py
When no siteType provided in new template, omit schema:additionalType from graph. Keep behavior the same for old template
> BDRSPS-1027 Remove default value from site vocab

- abis_mapping/base/mapper.py
- abis_mapping/templates/incidental_occurrence_data_v2/mapping.py
- abis_mapping/templates/incidental_occurrence_data_v3/mapping.py
- abis_mapping/templates/survey_metadata/mapping.py
- abis_mapping/templates/survey_metadata_v2/mapping.py
- abis_mapping/templates/survey_occurrence_data/mapping.py
- abis_mapping/templates/survey_occurrence_data_v2/mapping.py
- abis_mapping/templates/survey_site_data/mapping.py
- abis_mapping/templates/survey_site_data_v2/mapping.py
- tests/base/test_mapper.py
Call `extra_fields_schema(..., full_schema=False)` once per template, rather than once per row.
This is an expensive function, so this should give a noticeable performance improvement.
My testing locally shows a 13% speedup when mapping a incidental v3 template with 1000 rows.
Since all the rows of a template have the same extra fields, this is a safe refactor.
> BDRSPS-1029 Refactor so that extra_fields_schema is only called once per template mapping

- abis_mapping/templates/incidental_occurrence_data_v3/mapping.py
- abis_mapping/templates/survey_metadata_v2/mapping.py
- abis_mapping/templates/survey_occurrence_data_v2/mapping.py
- abis_mapping/templates/survey_site_data_v2/mapping.py
- abis_mapping/templates/survey_site_visit_data_v2/mapping.py
Every chunk of RDF output should include a `<...> a tern:Dataset` triple, to make them valid RDF
> BDRSPS-1038 Ensure that every chunk has a dataset type triple

- README.md
- abis_mapping/plugins/__init__.py
- abis_mapping/plugins/string_customized.py
- tests/plugins/test_customized_string.py
This custom field is set to override the default frictionless string field.
It converts whitespace-only cells to the empty string before the regular frictionless validation/checks occur.
This means that
1. a required field will error when supplied with a whitespace-only cell.
2. All strings fields will appear an `None` when mapping, when their cell is whitespace-only (i.e. behave the same as an empty cell)
> BDRSPS-1068 Add custom string field to treat whitespace-only cells as empty

- .github/workflows/testing.yml
- abis_mapping/templates/incidental_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data_v3/mapping.py
- abis_mapping/templates/incidental_occurrence_data_v3/validators/validator.ttl
- abis_mapping/templates/survey_metadata_v2/examples/minimal.ttl
- abis_mapping/templates/survey_metadata_v2/mapping.py
- abis_mapping/templates/survey_occurrence_data_v2/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v2/mapping.py
- abis_mapping/templates/survey_occurrence_data_v2/validators/validator.ttl
- abis_mapping/templates/survey_site_data_v2/examples/minimal.ttl
- abis_mapping/templates/survey_site_data_v2/mapping.py
- abis_mapping/templates/survey_site_visit_data_v2/examples/minimal.ttl
- abis_mapping/templates/survey_site_visit_data_v2/mapping.py
Swap predicate as per feedback.
I also tweaked the python matrix test logic.
Typically, when one fails, the others are at least 90% done, so there isn't much saving in failing fast.
I would rather see if the failure is for all py versions or just some.
> BDRSPS-1088 Swap `schema:identifier` for `schema:name` for attribute Collections

- pyproject.toml
This is mainly so the staging env shows abis-mapping as v6
> Start development of v6

- .github/workflows/documentation.yml
- .github/workflows/testing.yml
This is needed so CI continues to run for PRs that target the `release/v5` branch
> Make CI run on release branches and PRs into release branches

- abis_mapping/base/mapper.py
- abis_mapping/templates/incidental_occurrence_data_v3/mapping.py
- abis_mapping/templates/survey_metadata_v2/mapping.py
- abis_mapping/templates/survey_occurrence_data_v2/mapping.py
- abis_mapping/templates/survey_site_data_v2/mapping.py
- abis_mapping/templates/survey_site_visit_data_v2/mapping.py
- scripts/generate_example_ttl_files.py
- tests/base/test_mapper.py
- tests/templates/test_mapping.py
- tests/templates/test_survey_occurrence_data_v2.py
Each mapper class previously had very similar versions of the `apply_mapping` method. 
This has been refactored to a single method on the base class.
Now `apply_mapping_row` is the abstract method each subclass must implement
> BDRSPS-1118 Refactor `apply_mapping` method by moving it to the base mapper class

- abis_mapping/templates/survey_metadata_v3/examples/minimal.ttl
- abis_mapping/templates/survey_metadata_v3/mapping.py
- abis_mapping/utils/iri_patterns.py
Merge #372 First
So that the same attribution across multiple rows coalesces into one piece of RDF.
> BDRSPS-1131 Make datatype attributions named nodes in metadata mapping

- abis_mapping/base/mapper.py
- abis_mapping/models/metadata.py
- tests/base/test_mapper.py
- tests/templates/test_common.py
This is important since this method is cached, we don't want to the value stored in the cache to be mutated, which would effect future calls to the function.
> BDRSPS-1122 Make mapper `metadata` method return a frozen class instead of a dict

- abis_mapping/base/mapper.py
- abis_mapping/templates/incidental_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_metadata_v2/examples/minimal.ttl
- abis_mapping/templates/survey_metadata_v3/examples/minimal.ttl
- abis_mapping/templates/survey_occurrence_data_v2/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v2/examples/organism_qty.ttl
- abis_mapping/templates/survey_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v3/examples/organism_qty.ttl
- abis_mapping/templates/survey_site_data_v2/examples/minimal.ttl
- abis_mapping/templates/survey_site_data_v3/examples/minimal.ttl
- abis_mapping/templates/survey_site_visit_data_v2/examples/minimal.ttl
- abis_mapping/templates/survey_site_visit_data_v3/examples/minimal.ttl
- tests/templates/test_survey_occurrence_data_v2.py
- tests/templates/test_survey_occurrence_data_v3.py
Full details of the submission are mapped elsewhere in the dataset.ttl output file.
This is so each chunk can be independently validated.
> BDRSPS-1175 Add mapping for the Submission type to every chunk

- abis_mapping/base/mapper.py
- abis_mapping/templates/survey_metadata_v2/examples/minimal.ttl
- abis_mapping/templates/survey_metadata_v2/mapping.py
- abis_mapping/templates/survey_metadata_v3/examples/minimal.ttl
- abis_mapping/templates/survey_metadata_v3/mapping.py
- abis_mapping/templates/survey_site_visit_data_v3/examples/minimal.ttl
- scripts/generate_example_ttl_files.py
- tests/helpers.py
- tests/templates/test_mapping.py
- tests/templates/test_survey_occurrence_data_v2.py
- tests/templates/test_survey_occurrence_data_v3.py
When the metadata form v2 is being used (`submission_iri` is not None):
* Don't create a new project IRI, use the one from metadata form v2 mapping.
* Don't add properties to the project that are created in the metadata form v2 mapping
* Omit mapping the project all together if there is no project in the metadata form v2 mapping.
This uses a new `project_iri` argument which receives the project iri from the metadata form v2 mapping
> BDRSPS-1177 Update abis:Project mapping when new metadata v2 form is being used

- abis_mapping/templates/survey_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v3/examples/organism_qty.ttl
- abis_mapping/templates/survey_occurrence_data_v3/mapping.py
- abis_mapping/templates/survey_site_data_v3/examples/minimal.ttl
- abis_mapping/templates/survey_site_data_v3/mapping.py
- abis_mapping/templates/survey_site_visit_data_v3/examples/minimal.ttl
- abis_mapping/templates/survey_site_visit_data_v3/mapping.py
Previously it was only added when the existingBDRSiteIRI field was provided, due to a misinterpretation of the spec.
> BDRSPS-1186 Always include Site schema:identifier in mapping when siteID field is available

- abis_mapping/plugins/__init__.py
- abis_mapping/plugins/geometry_validation.py
- abis_mapping/plugins/sites_geometry.py
- abis_mapping/templates/survey_occurrence_data_v3/mapping.py
- tests/templates/test_survey_occurrence_data_v3.py
When an occurrence uses existingBDRSiteIRI, the following are allowed:
* The Occurrence has no geometry, and
* The Site is not in the site template, and
* The Site is in the site template, but has no geometry.
This means we need to account for there being no geometry available when mapping an occurrence. In this case we just omit the geometry related-RDF from the output.
> BDRSPS-1199 Relax occurrence geometry/site validation when using existingBDRSiteIRI

- abis_mapping/templates/incidental_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data_v3/mapping.py
- abis_mapping/templates/survey_metadata_v2/mapping.py
- abis_mapping/templates/survey_metadata_v3/mapping.py
- abis_mapping/templates/survey_occurrence_data_v2/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v2/mapping.py
- abis_mapping/templates/survey_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v3/mapping.py
- abis_mapping/utils/iri_patterns.py
- abis_mapping/utils/rdf.py
- abis_mapping/utils/vocabs.py
- abis_mapping/vocabs/threat_status.py
- tests/utils/test_rdf.py
Add new `uri_slugified()` function and use it everywhere appropriate, so that slashes (`/`) in field values are replaced with dashes when being slugified.
The old function `uri()` purposely kept slashes, this was intended for keeping slashes **between** field values, but unintentionally also kept slashes **in** field values.
Since `uri()` is now only ever called with static values, its slugifying has been removed, since all static values passed to it are already slugified.
Also did a improvement so `agent_iri()` is only called when there is an actual value in the field being used for the IRI.
> BDRSPS-1203 Fix slugify-ing slashes in values

- abis_mapping/templates/incidental_occurrence_data_v3/mapping.py
- abis_mapping/templates/survey_occurrence_data_v2/mapping.py
- abis_mapping/templates/survey_occurrence_data_v3/mapping.py
- abis_mapping/utils/iri_patterns.py
This ensures that its impossible for two different record IDs, to resolve to the same IRI.
This was possible when the record ID was being slugified.
This is also consistent with our convention of url-quote IDs, slugify other values.
> BDRSPS-1205 Url-quote providerRecordID when used in IRIs

- abis_mapping/utils/rdf.py
Since this is often called with the same string inputs
> BDRSPS-1216 Cache `quote_for_uri()`

- abis_mapping/base/mapper.py
- abis_mapping/models/schema.py
- abis_mapping/templates/survey_metadata_v3/mapping.py
- abis_mapping/templates/survey_occurrence_data_v3/mapping.py
- abis_mapping/templates/survey_site_data_v3/mapping.py
- abis_mapping/templates/survey_site_visit_data_v3/mapping.py
- docs/models/markdown/Schema.schema.md
- tests/base/test_mapper.py
- tests/templates/test_common.py
The `fields()` method does an expensive `models.schema.Schema.model_validate(...)` call,
but is also called multiple times per row when mapping.
This PR adds a `functools.cache` to it, so the return values is cached per mapper class.
To the prevent the cached value being mutated, it also makes its return value immutable.
It also refactors some repeated code into a new `regular_fields_schema` method.
> BDRSPS-1213 Cache `fields()` mapper method

- poetry.lock
- pyproject.toml
This helps to catch warnings like Deprecations earlier, rather than later.
> BDRSPS-796 Check for warnings in tests

- abis_mapping/templates/incidental_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_metadata_v3/examples/minimal.ttl
- abis_mapping/templates/survey_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v3/examples/organism_qty.ttl
- abis_mapping/templates/survey_site_data_v3/examples/minimal.ttl
- scripts/generate_example_ttl_files.py
so the output is the same on windows and linux
Note: all the `.ttl` diff is because the script was last ran and committed on windows, this PR returns it to the linux output,
which should also be the output on windows once this PR is merged.
> BDRSS-656 Fix generate_example_ttl_files.py script 
