- abis_mapping/templates/dwc_mvp/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/dwc_mvp/mapping.py
* Adds 3 new concepts from TERN (See BDR-440)
* Updates generated `margaret_river_flora.ttl` with new output
> BDR-440: Update vocab concepts with new values from TERN

- abis_mapping/templates/dwc_mvp/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/dwc_mvp/mapping.py
- abis_mapping/templates/dwc_mvp/schema.json
* Updated mapping to match new requirements
* Updated unit tests
* `dateIdentified` is now optional in the csv/schema
> BDR-525: Mapping Updates

- abis_mapping/templates/dwc_mvp/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/dwc_mvp/mapping.py
- abis_mapping/utils/namespaces.py
* As discussed:
* Changes all placeholder concept IRIs from `createme.org` to `example.com`
* Adds `void:inDataset` to all Samplings
* Updates unit tests to match
> BDR-635 Interim changes to match new minimal validation

- abis_mapping/templates/dwc_mvp/metadata.json
* This creates necessary values in the schema so that we can place them in the frontend.
* Does not include refactoring of template id
> BDR-583 Additional properties in the metadata schema for templates

- abis_mapping/templates/occurrence_data/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/occurrence_data/mapping.py
- abis_mapping/utils/vocabs.py
- tests/utils/test_vocabs.py
* As per BDR-646, it is actually much better if we include a `dcterms:source` with our 'on-the-fly' vocabs
* This PR adds an optional `source` keyword to flexible vocabs to add said term
> BDR-646: Add dataset as source for newly created concepts

- abis_mapping/plugins/tabular.py
- abis_mapping/templates/occurrence_data/mapping.py
- abis_mapping/templates/occurrence_extended/mapping.py
- tests/plugins/test_tabular.py
* Rename `NotTabular` to `IsTabular` as per: https://github.com/gaiaresources/abis-mapping/pull/38#discussion_r970228830
> BDRC-67: Rename `NotTabular` to `IsTabular`

- pyproject.toml
* Bumps `pyproject.toml` package version from `1.0.0` -> `2.0.0`
> Bump package version from `1.0.0` -> `2.0.0`

- abis_mapping/templates/occurrence_extended/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/occurrence_extended/schema.json
- abis_mapping/vocabs/conservation_jurisdiction.py
- abis_mapping/vocabs/threat_status.py
* See: BDRC-58
* Adds new `conservationJurisdiction` vocab terms
* Adds new `threatStatus` vocab terms
> BDRC-58: New `conservationJurisdiction` and `threatStatus` Vocab Terms

- abis_mapping/templates/incidental_occurrence_data/metadata.json
- abis_mapping/templates/survey_occurrence_data/metadata.json
- tests/templates/test_incidental_occurrence_data.py
- tests/templates/test_survey_occurrence_data.py
this branch adds the new sampling_type field. It is branched from BDRSPS-108 so PR #51 should be actioned beforehand.
> BDRSPS-102 Added sampling_type field to metadata.json

- tests/plugins/test_chronological.py
- tests/templates/test_incidental_occurrence_data.py
- tests/templates/test_survey_metadata.py
- tests/templates/test_survey_occurrence_data.py
- tests/utils/test_timestamps.py
This will fix the mypy errors inadvertently introduced in testing files surrounding the chronological check mainly.
> BDRSPS-129: Fix mypy errors introduced

- abis_mapping/base/mapper.py
- tests/base/test_mapper.py
- tests/templates/test_incidental_occurrence_data.py
Created two extra methods to achieve this
- One that takes either raw data or a frictionless row and produces a "diff" schema
- Another that takes a frictionless row, produces diff schema from it then returns a dictionary of the extra values
> BDRSPS-175: Extra fields csv parsing

- poetry.lock
- pyproject.toml
Finally something that works first time. This PR needs to coincide with the python3.11 update on PartA backend https://gitlab.gaiaresources.com.au/devs/bdr-parta/-/merge_requests/241.
> BDRSPS-171 Updated python and slugify

- abis_mapping/templates/survey_metadata/examples/minimal.ttl
- abis_mapping/templates/survey_metadata/examples/minimal_extra_cols.ttl
- abis_mapping/templates/survey_metadata/mapping.py
This was branched from BDRSPS-210 and as such will require [PR#64](https://github.com/gaiaresources/abis-mapping/pull/64) be approved first.
> BDRSPS-211 Modified and added survey methodology fields on graph.

- abis_mapping/base/mapper.py
- abis_mapping/templates/incidental_occurrence_data/mapping.py
- abis_mapping/templates/survey_metadata/mapping.py
- abis_mapping/templates/survey_occurrence_data/mapping.py
- abis_mapping/templates/survey_site_data/examples/minimal.ttl
- abis_mapping/templates/survey_site_data/examples/minimal_extra_cols.ttl
- abis_mapping/templates/survey_site_data/mapping.py
- abis_mapping/vocabs/__init__.py
- abis_mapping/vocabs/site_type.py
- tests/templates/test_survey_site_data.py
This adds the implementation of the site data template mapping. Changes include:
- Moved the default dataset method to the base mapper class and removed it from each of the templates to keep it DRY
- Added new site type vocab
- Implemented `apply_mapping` method of the site data template.
> BDRSPS-273 Implement SSD site data mapping

- abis_mapping/templates/survey_metadata/examples/minimal.ttl
- abis_mapping/templates/survey_metadata/examples/minimal_extra_cols.ttl
- abis_mapping/templates/survey_metadata/mapping.py
- abis_mapping/templates/survey_metadata/schema.json
Taxonomic coverage field now a string, and value now a bdr:target string literal value off of the bdr:survey node.
> BDRSPS-287 Updated survey metadata taxonomic coverage mapping

- abis_mapping/templates/survey_metadata/examples/minimal.ttl
- abis_mapping/templates/survey_metadata/examples/minimal_extra_cols.ttl
- abis_mapping/templates/survey_metadata/mapping.py
Changes as commented in option 2 rdf of [BDRSPS-300](https://youtrack.gaiaresources.com.au/youtrack/issue/BDRSPS-300/Update-Survey-model)
- Change bdr:hasSurvey to sdo:hasPart
- Change dcterms:description to bdr:purpose and move to Survey node
- Move sdo:keywords from Project to Survey
- Change sosa:Procedure to prov:Plan
- Change rdfs:isDefinedBy to sdo:url
- Change skos:definition to sdo:description
- Move bdr:purpose from Project to Survey
- Move sdo:keywords from Project to Survey
- Change sosa:usedProcedure to prov:hadPlan
> BDRSPS-320 Changes made to survey metadata template mapping.

- pyproject.toml
This in prevision for a new v3.2.0 release tag.
> Bumped package version to 3.2.0

- abis_mapping/base/mapper.py
- abis_mapping/templates/incidental_occurrence_data/mapping.py
- abis_mapping/templates/survey_metadata/mapping.py
- abis_mapping/templates/survey_occurrence_data/mapping.py
- abis_mapping/templates/survey_site_data/mapping.py
- tests/templates/test_common.py
refactored extra fields to be not be done using skip errors but by creating an extra fields schema before validating
> BDRSPS-481 Extra fields validation refactor

- abis_mapping/base/mapper.py
- abis_mapping/templates/incidental_occurrence_data/mapping.py
- abis_mapping/templates/survey_metadata/mapping.py
- abis_mapping/templates/survey_occurrence_data/mapping.py
- abis_mapping/templates/survey_site_data/mapping.py
- tests/base/test_mapper.py
- tests/templates/test_common.py
Will allow for more flexible usage of the template mapping and validation methods e.g. file io objects.
> BDRSPS-477 Changed all resource instantiations to use source arg instead of data

- abis_mapping/settings.py
- abis_mapping/templates/incidental_occurrence_data/mapping.py
- abis_mapping/templates/survey_metadata/mapping.py
- abis_mapping/templates/survey_occurrence_data/mapping.py
- abis_mapping/templates/survey_site_data/mapping.py
- abis_mapping/types/__init__.py
- abis_mapping/types/geometry.py
- abis_mapping/utils/geometry.py
- abis_mapping/utils/rdf.py
- poetry.lock
- pyproject.toml
- tests/templates/test_common.py
- tests/templates/test_survey_occurrence_data.py
- tests/types/test_geometry.py
- tests/utils/test_rdf.py
- Created `Geometry` class which is now intended to handle rdf wkt literal generation and ingestion as well as transformations into default CRS
- Pyproj added to achieve geometry transformations
- Decommissioned the wkt rdf literal functions as these are now included as methods of the `Geometry` class.
> BDRSPS-496 Implement geometry converter

- abis_mapping/base/mapper.py
- abis_mapping/templates/incidental_occurrence_data/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data/mapping.py
- abis_mapping/templates/survey_metadata/examples/minimal.ttl
- abis_mapping/templates/survey_metadata/examples/year.ttl
- abis_mapping/templates/survey_metadata/examples/yearmonth.ttl
- abis_mapping/templates/survey_metadata/mapping.py
- abis_mapping/templates/survey_occurrence_data/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data/examples/organism_qty.ttl
- abis_mapping/templates/survey_occurrence_data/mapping.py
- abis_mapping/templates/survey_site_data/examples/minimal.ttl
- abis_mapping/templates/survey_site_data/mapping.py
Mapped to maintain reference to the transformed geometry BNode in two locations each per graph.
> BDRSPS-507 Implemented mapping changes for transformed geometries

- tests/types/test_spatial.py
minor change to spatial tests to allow for future geographic CRS transform test cases.
> BDRSPS-524 Set up geometry tests for parametrization

- abis_mapping/templates/survey_metadata/metadata.json
- abis_mapping/templates/survey_occurrence_data/metadata.json
- tests/templates/conftest.py
Also fixed indenting on survey occurrence data medata.json.
> BDRSPS-546 Updated all ssd templates to v1.0.0.

- abis_mapping/templates/incidental_occurrence_data_v2/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data_v2/mapping.py
- abis_mapping/templates/incidental_occurrence_data_v2/schema.json
A minor change was also done to the schema, removing the mutually inclusive check between `providerRecordID` and `providerRecordIDSource` and making the latter *required* which is equivalent.
> BDRSPS-571 Implemented incidental mapping changes, removing reification for datatypes

- CHANGELOG.md
containing the changes to incidental occurrence
> BDRSPS-569 initiate an abis-mapping CHANGELOG with a diff of incidental occurrences between V1 and V2

- abis_mapping/templates/survey_site_data/mapping.py
- abis_mapping/types/spatial.py
- tests/templates/test_survey_site_data.py
- tests/types/test_spatial.py
This addresses the issue encountered during acceptance testing.
> BDRSPS-624: Added GeometryError and capturing during extraction of default geometries from site template.

- abis_mapping/base/mapper.py
- abis_mapping/templates/incidental_occurrence_data_v2/schema.json
- abis_mapping/templates/survey_metadata/schema.json
- abis_mapping/templates/survey_occurrence_data/schema.json
- abis_mapping/templates/survey_site_data/schema.json
- abis_mapping/types/schema.py
- tests/templates/test_common.py
Vocabs related to a field are now included as a list property for the field, except for incidental v1 template. Further work will be performed to better utilise this tie-in within the mapping methods.
> BDRSPS-654 Added vocabs to schema.json

- .github/workflows/ci.yml
- abis_mapping/templates/incidental_occurrence_data_v2/templates/instructions.md
- abis_mapping/templates/survey_occurrence_data/mapping.py
- docs/instructions.py
- docs/tables/base.py
- docs/tables/fields.py
- docs/tables/threat_status.py
- docs/tables/vocabs.py
- scripts/generate_instructions.sh
- tests/docs/tables/test_base.py
- tests/docs/tables/test_fields.py
- tests/docs/tables/test_threat_status.py
- tests/docs/tables/test_vocabs_tabler.py
Also added table column justification to match the incidental v2 instructions pdf alignments.
> BDRSPS-698 Added anchors and links to generated instructions.

- .github/workflows/ci.yml
- abis_mapping/templates/incidental_occurrence_data_v2/templates/instructions.md
- abis_mapping/templates/survey_occurrence_data/mapping.py
- docs/instructions.py
- docs/tables/base.py
- docs/tables/fields.py
- docs/tables/threat_status.py
- docs/tables/vocabs.py
- scripts/generate_instructions.sh
- tests/docs/tables/test_base.py
- tests/docs/tables/test_fields.py
- tests/docs/tables/test_threat_status.py
- tests/docs/tables/test_vocabs_tabler.py
Removed alphabetical sorting. This branch was created using BDRSPS-698 as a base, meaning PR#164 should be reviewed and approved first.
> BDRSPS-706 Field sort order should be as per csv template for instructions

- abis_mapping/templates/incidental_occurrence_data_v2/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data_v2/mapping.py
- abis_mapping/templates/incidental_occurrence_data_v2/schema.json
- abis_mapping/templates/survey_occurrence_data/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data/examples/organism_qty.ttl
- abis_mapping/templates/survey_occurrence_data/mapping.py
- abis_mapping/templates/survey_occurrence_data/schema.json
- abis_mapping/vocabs/kingdom.py
- tests/templates/test_mapping.py
removed kingdom attribute from current templates and left deprecation comment on associated controlled vocabulary.
> BDRSPS-703 Remove kingdom attribute from templates

- abis_mapping/templates/incidental_occurrence_data_v2/schema.json
- abis_mapping/templates/incidental_occurrence_data_v2/templates/instructions.md
- abis_mapping/templates/survey_occurrence_data/schema.json
- abis_mapping/templates/survey_occurrence_data/templates/instructions.md
- abis_mapping/vocabs/kingdom.py
- docs/tables/vocabs.py
- scripts/generate_instructions.sh
and associated rendering logic. This also fixes the issue caused by removing KINGDOM controlled vocabulary from the occurrence mappers, by altering the row generation logic for the controlled vocabs' tables.
> BDRSPS-556 Created survey occurrence instructions markdown template

- abis_mapping/templates/incidental_occurrence_data/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data_v2/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/utils/vocabs.py
- abis_mapping/vocabs/kingdom.py
...by appending `specimen` and `occurrence` to new concept `skos:prefLabel` predicated object literals.
> BDRSPS-703 Modified Kingdom Specimen and Occurrence vocab mappings

- abis_mapping/templates/survey_metadata/templates/instructions.md
- abis_mapping/templates/survey_occurrence_data/templates/instructions.md
- abis_mapping/templates/survey_site_data/schema.json
- abis_mapping/templates/survey_site_data/templates/instructions.md
- docs/contexts/__init__.py
- docs/contexts/survey_site_data.py
- scripts/generate_instructions.sh
Also fixed formatting issues with existing templates.
> BDRSPS-558 Added the survey site data instructions template and generating logic

- pyproject.toml
@Lincoln-GR or @joecrowleygaia could one of you merge that
> BDRSPS-741: bumped version to 4.2.1.

- abis_mapping/templates/incidental_occurrence_data_v2/templates/instructions.md
- abis_mapping/templates/survey_metadata/templates/instructions.md
- abis_mapping/templates/survey_occurrence_data/templates/instructions.md
- abis_mapping/templates/survey_site_data/templates/instructions.md
fixed instruction appendix indentation and numbering for markdown templates.
> BDRSPS-736 Fixes minor issues with appendix heading formatting.

- abis_mapping/templates/incidental_occurrence_data_v2/schema.json
- abis_mapping/templates/survey_metadata/schema.json
- abis_mapping/templates/survey_occurrence_data/schema.json
- abis_mapping/templates/survey_site_data/schema.json
- abis_mapping/types/schema.py
- docs/contexts/incidental_occurrence_data_v2.py
- docs/contexts/survey_metadata.py
- docs/contexts/survey_occurrence_data.py
- docs/contexts/survey_site_data.py
- docs/tables/base.py
- docs/tables/fields.py
- docs/tables/threat_status.py
- docs/tables/vocabs.py
- tests/docs/conftest.py
- tests/docs/tables/test_base.py
- tests/docs/tables/test_fields.py
- tests/docs/tables/test_threat_status.py
- tests/docs/tables/test_vocabs_tabler.py
Also cleans up some code duplication for the tabler classes.
> BDRSPS-712 Adds Darwin core links to field names in markdown tables

- .gitignore
- abis_mapping/templates/incidental_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data_v3/mapping.py
- abis_mapping/templates/survey_occurrence_data_v2/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v2/mapping.py
- tests/conftest.py
- tests/templates/under_development/test_mapping_udev.py
To allow identifier RDF changes.
The temporary tests created are in place to help with further development prior to v5 release. To test yourself perform something like `PYTEST_NO_SKIPS=True pytest tests/templates/under_development/`
> BDRSPS-737 Made mapping changes to the newest occurrence templates

- abis_mapping/templates/incidental_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data_v3/mapping.py
- abis_mapping/templates/incidental_occurrence_data_v3/validators/validator.ttl
- abis_mapping/templates/survey_occurrence_data_v2/validators/validator.ttl
- tests/templates/under_development/test_mapping_udev.py
Doesn't complete the ticket but brings it slightly closer to completion. Awaiting mapping detail from others.
> BDRSPS-737 Added shacl files and validation tests for datatypes changes.

- abis_mapping/templates/incidental_occurrence_data/metadata.json
- abis_mapping/templates/incidental_occurrence_data_v2/metadata.json
- abis_mapping/templates/incidental_occurrence_data_v3/metadata.json
- abis_mapping/templates/survey_metadata/metadata.json
- abis_mapping/templates/survey_metadata_v2/metadata.json
- abis_mapping/templates/survey_occurrence_data/metadata.json
- abis_mapping/templates/survey_occurrence_data_v2/metadata.json
- abis_mapping/templates/survey_site_data/metadata.json
- abis_mapping/templates/survey_site_data_v2/metadata.json
- abis_mapping/templates/survey_site_visit_data_v2/metadata.json
- abis_mapping/types/metadata.py
Can be used by applications to allow filtering based on status.
> BDRSPS-802: Added status field to metadata to indicate template stage in its lifecycle.

- abis_mapping/templates/incidental_occurrence_data/metadata.json
- abis_mapping/templates/incidental_occurrence_data_v2/metadata.json
- abis_mapping/templates/incidental_occurrence_data_v3/metadata.json
- abis_mapping/templates/survey_metadata/metadata.json
- abis_mapping/templates/survey_metadata_v2/metadata.json
- abis_mapping/templates/survey_occurrence_data/metadata.json
- abis_mapping/templates/survey_occurrence_data_v2/metadata.json
- abis_mapping/templates/survey_site_data/metadata.json
- abis_mapping/templates/survey_site_data_v2/metadata.json
- abis_mapping/templates/survey_site_visit_data_v2/metadata.json
- abis_mapping/types/metadata.py
This reverts commit 87ecec3a3263f8b5154961112535adba0c6bc733. No longer required.
> BDRSPS-802 Revert "added status field to metadata to indicate template stage in its lifecycle."

- abis_mapping/templates/incidental_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data_v3/mapping.py
Rename `conservationJurisdiction` to `conservationAuthority` in the attributes and values in the RDF output for incidental template V3
> BDRSPS-813 Incidental V3: Rename conservationJurisdiction to conservationAuthority in RDF output

- abis_mapping/types/schema.py
- tests/base/test_mapper.py
restores returned serialization expected by current applications.
> BDRSPS-863 Modified serialization of url field to be string and not AnyUrl for fields model.

- abis_mapping/templates/survey_site_data_v2/examples/minimal-error-missing-fields.csv
- abis_mapping/templates/survey_site_data_v2/mapping.py
- tests/templates/conftest.py
* Remove validation of siteVisitStart and siteVisitEnd fields which were removed. 
* Add test case for invalid template with missing fields.
> BDRSPS-853 Update site data v2 csv validation

- .flake8
- .github/workflows/testing.yml
- abis_mapping/plugins/chronological.py
- abis_mapping/plugins/list.py
- abis_mapping/plugins/timestamp.py
- abis_mapping/plugins/wkt.py
- abis_mapping/templates/incidental_occurrence_data_v3/mapping.py
- abis_mapping/templates/survey_site_data/validators/shaping.py
- abis_mapping/templates/survey_site_data_v2/validators/shaping.py
- abis_mapping/types/temporal.py
- abis_mapping/utils/vocabs.py
- docs/instructions.py
- docs/tables/base.py
- docs/tables/threat_status.py
- poetry.lock
- pyproject.toml
- tests/base/test_mapper.py
- tests/docs/test_instructions.py
- tests/plugins/test_list.py
- tests/plugins/test_site_geometry.py
- tests/templates/test_mapping.py
- tests/templates/test_survey_occurrence_data.py
- tests/templates/test_survey_site_data.py
- tests/templates/test_validation.py
- tests/types/test_temporal.py
This PR swaps our linting tool from flake8 to ruff.
Some more rules are enabled for consistency with part-a, this PR fixes those.
> Swap to ruff for linting

- .github/workflows/documentation.yml
- .github/workflows/testing.yml
- poetry.lock
- pyproject.toml
- scripts/lint.sh
- scripts/test.sh
- scripts/typecheck.sh
Making so can easily run CI checks on local machine before pushing
> BDRSPS-877 Added poe the poet and removed unused scripts.

- scripts/generate_instructions.sh
This should make the github CI fail if there are errors in this script, like before
> Set generate_instructions.sh script to exit if any build commands exit with error

- .git-blame-ignore-revs
- abis_mapping/templates/incidental_occurrence_data/mapping.py
- abis_mapping/templates/incidental_occurrence_data_v2/mapping.py
- abis_mapping/templates/incidental_occurrence_data_v3/mapping.py
- abis_mapping/templates/survey_occurrence_data/mapping.py
- abis_mapping/templates/survey_occurrence_data_v2/mapping.py
- abis_mapping/templates/survey_site_data/mapping.py
- abis_mapping/templates/survey_site_data_v2/mapping.py
- abis_mapping/vocabs/check_protocol.py
- abis_mapping/vocabs/establishment_means.py
- abis_mapping/vocabs/identification_qualifier.py
- abis_mapping/vocabs/threat_status.py
- docs/tables/threat_status.py
- pyproject.toml
- tests/templates/under_development/test_mapping_udev.py
- tests/types/test_metadata.py
- tests/types/test_spatial.py
> Lint unused suppressions 2

- scripts/generate_instructions.sh
This was branched from BDRSPS-832 and so [PR#236](https://github.com/gaiaresources/abis-mapping/pull/236) should be applied first.
> Bdrsps 833: Added incidental occurrence v3 to generated instructions

- CHANGELOG.md
- abis_mapping/templates/incidental_occurrence_data_v2/templates/instructions.md
- abis_mapping/templates/incidental_occurrence_data_v3/templates/instructions.md
- docs/tables/fields.py
- poetry.lock
- tests/docs/tables/test_fields.py
* Add changelog for incidental v3
* Add changelogs to instructions documents
> BDRSPS-764 Add template changelogs

- abis_mapping/templates/survey_site_data_v2/templates/instructions.md
- docs/contexts/__init__.py
- docs/contexts/survey_site_data_v2.py
Prepares the site v2 docs by setting up their context, and some minor changes to the doc.
> BDRSPS-859 Prepare survey site v2 documentation

- abis_mapping/templates/survey_metadata_v2/mapping.py
- scripts/generate_instructions.sh
* Register Survey metadata template v2
* Add Survey metadata v2 instructions to docs site.
> BDRSPS-846 and BDRSPS-858 Register Survey metadata v2

- abis_mapping/templates/survey_metadata/templates/instructions.md
- abis_mapping/templates/survey_metadata_v2/templates/instructions.md
- abis_mapping/templates/survey_occurrence_data/templates/instructions.md
- abis_mapping/templates/survey_occurrence_data_v2/templates/instructions.md
- abis_mapping/templates/survey_site_data/templates/instructions.md
- abis_mapping/templates/survey_site_data_v2/templates/instructions.md
- docs/contexts/__init__.py
- docs/contexts/survey_occurrence_data_v2.py
- scripts/generate_instructions.sh
Also, fixed typos within instructions' markdown templates preventing bullet points to render in mkdocs for the 'NEED TO KNOW' sections.
> BDRSPS-842 Added survey occurrence v2 instructions context and generation to script

- CHANGELOG.md
- abis_mapping/templates/incidental_occurrence_data_v3/templates/instructions.md
- abis_mapping/templates/survey_occurrence_data_v2/templates/instructions.md
The concept of this field has changed more than a simple 'rename', so use the term 'replaced' instead.
> BDRSPS-880 Clarify changelog entry for conservationAuthority

- abis_mapping/base/mapper.py
- abis_mapping/base/validators/shapes.ttl
- abis_mapping/templates/incidental_occurrence_data/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data/mapping.py
- abis_mapping/templates/incidental_occurrence_data_v2/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data_v2/mapping.py
- abis_mapping/templates/incidental_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data_v3/mapping.py
- abis_mapping/templates/incidental_occurrence_data_v3/validators/validator.ttl
- abis_mapping/templates/survey_metadata/examples/minimal.ttl
- abis_mapping/templates/survey_metadata/mapping.py
- abis_mapping/templates/survey_metadata_v2/examples/minimal.ttl
- abis_mapping/templates/survey_metadata_v2/mapping.py
- abis_mapping/templates/survey_occurrence_data/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data/examples/organism_qty.ttl
- abis_mapping/templates/survey_occurrence_data/mapping.py
- abis_mapping/templates/survey_occurrence_data_v2/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v2/examples/organism_qty.ttl
- abis_mapping/templates/survey_occurrence_data_v2/mapping.py
- abis_mapping/templates/survey_occurrence_data_v2/validators/validator.ttl
- abis_mapping/templates/survey_site_data/examples/minimal.ttl
- abis_mapping/templates/survey_site_data/mapping.py
- abis_mapping/templates/survey_site_data_v2/mapping.py
- tests/templates/conftest.py
- tests/templates/test_mapping.py
Includes named nodes for attributions and altering the default dataset creation to conform to the new spec.
> BDRSPS-737 Implemented id datatype changes

- abis_mapping/types/spatial.py
As per pyproj docs: https://pyproj4.github.io/pyproj/stable/advanced_examples.html#caching-pyproj-objects.
I'm using `functools.cache` instead of `functools.lru_cache` because there are only so many datums, so the cache can only grow so large, so we don't need the "lru" eviction logic.
> BDRSPS-909 Cache the creation of pyproj objects

- abis_mapping/base/mapper.py
- abis_mapping/templates/survey_site_data_v2/examples/minimal.csv
- abis_mapping/templates/survey_site_data_v2/examples/minimal.ttl
- abis_mapping/templates/survey_site_data_v2/mapping.py
- abis_mapping/utils/rdf.py
- scripts/generate_instructions.sh
- tests/utils/test_rdf.py
* Remove mapping for removed fields
* Add mapping for new locality field
* Change coordinateUncertaintyInMeters mapping as per BDRSPS-914
* Change attribute mapping for habitat and dataGeneralizations as per BDRSPS-911
* Other small changes to RDF output
* Update example CSV to better test mapping output
* Register site data v2 template now that mapping is functional, so it is included in tests
* Add survey site data v2 to the docs site - part of BDRSPS-859
> BDRSPS-868 Survey site data v2 RDF mapping

- docs/templates/base.md
- mkdocs.yml
> BDRSPS-904 Add notices to docs when a template is deprecated or in beta.

- abis_mapping/templates/survey_metadata/examples/minimal.ttl
- abis_mapping/vocabs/sampling_effort_unit.py
* Add terms
* Add proper definition
* remove broader - not needed
* publish in docs
> BDRSPS-922 Implement SamplingEffortUnit vocab

- abis_mapping/templates/survey_occurrence_data_v2/templates/instructions.md
- abis_mapping/vocabs/check_protocol.py
- abis_mapping/vocabs/identification_method.py
- abis_mapping/vocabs/sensitivity_authority.py
- abis_mapping/vocabs/sensitivity_category.py
- abis_mapping/vocabs/sequencing_method.py
- docs/tables/vocabs.py
- tests/docs/tables/test_vocabs_tabler.py
Updated the vocabs tabler to create TBC placeholder rows when no terms exist for it.
> BDRSPS-885 Made changes to survey occurrence v2 instructions. 

- abis_mapping/templates/survey_site_data_v2/examples/minimal.ttl
- abis_mapping/templates/survey_site_data_v2/mapping.py
The site is now linked to the attribute Sample Collections, this link is no longer required.
> BDRSPS-929 Remove link from sites to attributes.

- abis_mapping/templates/incidental_occurrence_data_v2/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data/examples/organism_qty.ttl
- abis_mapping/templates/survey_occurrence_data_v2/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v2/examples/organism_qty.ttl
- abis_mapping/vocabs/sampling_protocol.py
Also update broader IRI, and update default term
> BDRSPS-919 Update sampling Protocol vocab with new terms

- abis_mapping/templates/survey_site_data/mapping.py
- abis_mapping/templates/survey_site_data_v2/mapping.py
- abis_mapping/templates/survey_site_visit_data_v2/mapping.py
- tests/templates/test_survey_site_data.py
- tests/templates/test_survey_site_visit_data_v2.py
* Skip rows with no siteID when extracting geometry defaults
* make same fix for temporal defaults in case its a problem there
> BDRSPS-937 Skip rows with no siteID when extracting geometry defaults

- abis_mapping/templates/incidental_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data_v3/mapping.py
Fixup for #272 , similar to #277
> BDRSPS-925 Fix: swap tern:SampleCollection for tern:Collection in incidental v3 mapping

- abis_mapping/templates/incidental_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data_v3/mapping.py
- abis_mapping/templates/survey_occurrence_data_v2/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v2/mapping.py
- abis_mapping/templates/survey_site_data_v2/examples/minimal.ttl
- abis_mapping/templates/survey_site_data_v2/mapping.py
* Swap incorrect tern:Collection for schema:Collection
* Swap incorrect sosa:hasMember for schema:member in Collections
> BDRSPS-925 Minor fixes to Attribute Collections

- abis_mapping/templates/survey_site_visit_data_v2/examples/minimal-1-row.csv
- abis_mapping/templates/survey_site_visit_data_v2/examples/minimal.csv
- abis_mapping/templates/survey_site_visit_data_v2/examples/minimal.ttl
- abis_mapping/templates/survey_site_visit_data_v2/mapping.py
- abis_mapping/templates/survey_site_visit_data_v2/schema.json
- abis_mapping/utils/rdf.py
- tests/templates/conftest.py
- tests/templates/test_survey_site_visit_data_v2.py
- tests/utils/test_rdf.py
Implemented as per spec in BDRSPS-882
> BDRSPS-869 Implement Survey Site Visit Data RDF mapping

- abis_mapping/templates/survey_occurrence_data_v2/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v2/examples/organism_qty.ttl
- abis_mapping/templates/survey_occurrence_data_v2/mapping.py
Same changes as #292 , except for survey occurrence template
> BDRSPS-925 Implement collections for remaining attributes in Survey occurrence v2 template

- abis_mapping/templates/survey_site_visit_data_v2/schema.json
- abis_mapping/templates/survey_site_visit_data_v2/templates/instructions.md
- abis_mapping/vocabs/visit_protocol_name.py
- docs/contexts/__init__.py
- docs/contexts/survey_site_visit_data_v2.py
- docs/templates/base.md
- scripts/generate_instructions.sh
Adds instructions document for site visit data template
> BDRSPS-860 Survey site visit data template instructions

- abis_mapping/templates/survey_metadata_v2/examples/minimal.ttl
- abis_mapping/templates/survey_metadata_v2/mapping.py
* Make attribute collections be linked to the survey plan
* Add type to the survey id datatype node
* Remove survey method procedure node
> BDRSPS-967 Corrections to survey metadata v2 mapping

- abis_mapping/templates/incidental_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data_v3/mapping.py
- abis_mapping/utils/iri_patterns.py
* To always use the base_iri (not the dataset)
* To use helper functions from iri_patterns
* To follow the new IRI patterns standard
* Row number is no longer used for any IRIs
> BDRSPS-966 Update IRI construction for incidental v3 template

- abis_mapping/templates/survey_occurrence_data_v2/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v2/examples/organism_qty.ttl
- abis_mapping/templates/survey_occurrence_data_v2/mapping.py
* Same changes as what was applied to the incidental v3 template.
* To always use the base_iri (not the dataset)
* To use helper functions from iri_patterns
* To follow the new IRI patterns standard
* Row number is no longer used for any IRIs
> BDRSPS-966 Update IRI construction for Survey Occurrence v2 template

- abis_mapping/templates/survey_occurrence_data_v2/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v2/examples/organism_qty.ttl
- abis_mapping/templates/survey_occurrence_data_v2/mapping.py
- abis_mapping/templates/survey_site_data_v2/examples/minimal.ttl
- abis_mapping/templates/survey_site_data_v2/mapping.py
- abis_mapping/templates/survey_site_visit_data_v2/examples/minimal.ttl
- abis_mapping/templates/survey_site_visit_data_v2/mapping.py
- abis_mapping/utils/iri_patterns.py
Add pattern functions for constructing Site and Site Visit IRIs.
This should be the last changes required in the survey occurrence template
> BDRSPS-966 SSD Site and SiteVisit IRI construction

- abis_mapping/templates/incidental_occurrence_data_v3/mapping.py
- abis_mapping/templates/survey_metadata_v2/examples/minimal.ttl
- abis_mapping/templates/survey_metadata_v2/mapping.py
- abis_mapping/templates/survey_occurrence_data_v2/mapping.py
- abis_mapping/templates/survey_site_data_v2/examples/minimal.ttl
- abis_mapping/templates/survey_site_data_v2/mapping.py
- abis_mapping/templates/survey_site_visit_data_v2/examples/minimal.ttl
- abis_mapping/templates/survey_site_visit_data_v2/mapping.py
- abis_mapping/utils/iri_patterns.py
- abis_mapping/utils/rdf.py
- tests/utils/test_rdf.py
* BDRSPS-966 Update IRIs in site template v2 to follow new standard patterns
* BDRSPS-966 Update IRIs in site visit template v2 to follow new standard patterns
* Remove unused extend_uri functions
* Update survey plan IRI to new pattern to differentiate with site visit plans
* Add iri pattern function for prov:Plan nodes
* Add iri pattern function for prov:Attribution nodes
> BDRSPS-966 Further updates to IRI patterns

- abis_mapping/templates/incidental_occurrence_data_v3/mapping.py
Fixup to #314. Required so terms created on the fly use the base_iri (dataset namespace)
> BDRSPS-966 Supply base_iri to 2 vocabs in incidental template v3 mapping that need it

- abis_mapping/templates/incidental_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data_v3/mapping.py
- abis_mapping/templates/survey_occurrence_data_v2/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v2/mapping.py
This is a change following up the change to using a dwc:Occurrence node.
> BDRSPS-1007 Change scientificName and threatStatus observations to always have occurrence as the featureOfInterest

- abis_mapping/templates/survey_site_data_v2/examples/minimal.csv
- abis_mapping/templates/survey_site_data_v2/examples/minimal.ttl
- abis_mapping/templates/survey_site_data_v2/mapping.py
Applied only to the site data v2 template.
> BDRSPS-1025 Made related site node type and value be dependent on the value of the relationshipToRelatedSite field of the site template.

- abis_mapping/templates/incidental_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data_v3/mapping.py
- abis_mapping/templates/survey_occurrence_data_v2/examples/organism_qty.ttl
- abis_mapping/templates/survey_occurrence_data_v2/mapping.py
Change organism quantity observation result tern:Value label to "organism-quantity"
> BDRSPS-1032 Change organism quantity value label

- docs/tables/fields.py
- tests/docs/tables/test_fields.py
As per specification provided.
> BDRSPS-1035 Created new column for field location on templates for instructions.

- abis_mapping/templates/incidental_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data_v3/mapping.py
- abis_mapping/templates/survey_occurrence_data_v2/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v2/examples/organism_qty.ttl
- abis_mapping/templates/survey_occurrence_data_v2/mapping.py
Note not using `void:inDataset` for the predicate, there will a following ticket converting the existing ones of those to use `schema:isPartOf`, same as here
> BDRSPS-1082 Add link to dataset from BiodiversityRecord

- abis_mapping/templates/incidental_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data_v3/mapping.py
- abis_mapping/templates/incidental_occurrence_data_v3/validators/validator.ttl
- abis_mapping/templates/survey_metadata_v2/examples/minimal.ttl
- abis_mapping/templates/survey_metadata_v2/mapping.py
- abis_mapping/templates/survey_occurrence_data_v2/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v2/examples/organism_qty.ttl
- abis_mapping/templates/survey_occurrence_data_v2/mapping.py
- abis_mapping/templates/survey_occurrence_data_v2/validators/validator.ttl
- abis_mapping/templates/survey_site_data_v2/examples/minimal.ttl
- abis_mapping/templates/survey_site_data_v2/mapping.py
- abis_mapping/templates/survey_site_visit_data_v2/examples/minimal.ttl
- abis_mapping/templates/survey_site_visit_data_v2/mapping.py
Every subject that has a `(..., void:inDataset, <dataset>)` triple, swap the `void:inDataset` predicate for `schema:isPartOf`
> BDRSPS-1084 Swap all void:inDataset predicates to schema:isPartOf

- .mypy.ini
See https://docs.pydantic.dev/latest/integrations/mypy/
> BDRSPS-1087 Enable pydantic plugin for better type-checking

- .gitignore
- README.md
- abis_mapping/models/metadata.py
- abis_mapping/models/spatial.py
- abis_mapping/plugins/wkt.py
- abis_mapping/settings.py
- poetry.lock
- pyproject.toml
- tests/conftest.py
- tests/helpers.py
- tests/models/test_metadata.py
- tests/models/test_spatial.py
- tests/utils/test_helpers.py
* Removed unused setting
* always use `settings.SETTINGS` rather than `settings.Settings()`
* make global settings object frozen
* ignore env vars / dotenv file when running tests
> BDRSPS-1089 Various improvements to settings

- abis_mapping/templates/incidental_occurrence_data_v3/templates/instructions.md
- abis_mapping/templates/survey_metadata_v2/templates/instructions.md
- abis_mapping/templates/survey_occurrence_data_v2/templates/instructions.md
- abis_mapping/templates/survey_site_data_v2/templates/instructions.md
- abis_mapping/templates/survey_site_visit_data_v2/templates/instructions.md
> BDRSPS-1008 Add instructions for template file name requirements

- pyproject.toml
I think we're good to v5.0.0.0-rc3
> BDRSPS-1080 bump version to v5.0.0-rc3

- .github/workflows/documentation.yml
- .github/workflows/testing.yml
> Backport v5: Make CI run on release branches and PRs into release branches

- abis_mapping/base/mapper.py
- abis_mapping/templates/incidental_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data_v3/mapping.py
- abis_mapping/templates/survey_metadata_v2/examples/minimal.ttl
- abis_mapping/templates/survey_metadata_v2/mapping.py
- abis_mapping/templates/survey_occurrence_data_v2/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v2/examples/organism_qty.ttl
- abis_mapping/templates/survey_occurrence_data_v2/mapping.py
- abis_mapping/templates/survey_site_data_v2/examples/minimal.ttl
- abis_mapping/templates/survey_site_data_v2/mapping.py
- abis_mapping/templates/survey_site_visit_data_v2/examples/minimal.ttl
- abis_mapping/templates/survey_site_visit_data_v2/mapping.py
- abis_mapping/utils/iri_patterns.py
- abis_mapping/utils/namespaces.py
- abis_mapping/utils/rdf.py
- abis_mapping/utils/vocabs.py
- scripts/generate_example_ttl_files.py
- tests/helpers.py
- tests/templates/test_mapping.py
- tests/templates/test_survey_occurrence_data_v2.py
- tests/utils/test_rdf.py
- tests/vocabs/test_organism_quantity_type.py
* Make `dataset_iri` and `base_iri` non-nullable arguments to `apply_mapping()`
* remove createme namespace
* remove default dataset mapping - no longer used
> BDRSPS-1123 Make dataset_iri and base_iri non-nullable

- docs/tables/base.py
- poetry.lock
- pyproject.toml
Add temporary type ignore due to mypy issue https://github.com/python/typeshed/issues/13293
> BDRSPS-1137 Upgrade mypy to 1.14.1

- abis_mapping/templates/survey_metadata_v3/examples/minimal.ttl
- abis_mapping/templates/survey_metadata_v3/mapping.py
Add links from the tern:Survey, tern:Attribute and schema:Collection to the submission
> BDRSPS-1173 Add links to Submission from the survey metadata v3 template

- abis_mapping/templates/incidental_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data_v3/schema.json
- abis_mapping/templates/survey_occurrence_data_v2/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v2/schema.json
- abis_mapping/templates/survey_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v3/schema.json
- abis_mapping/templates/survey_site_data_v2/schema.json
- abis_mapping/templates/survey_site_data_v3/schema.json
- abis_mapping/vocabs/__init__.py
- abis_mapping/vocabs/habitat.py
This has the same Terms as the "TARGET_HABITAT_SCOPE" vocab, but needs the terms created on-the-fly to be slightly different.
> BDRSPS-1184 Create dedicated "HABITAT" vocab for the habitat field in occurrence and site templates.

- abis_mapping/templates/survey_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v3/examples/organism_qty.ttl
- abis_mapping/templates/survey_occurrence_data_v3/mapping.py
- abis_mapping/templates/survey_occurrence_data_v3/schema.json
- abis_mapping/templates/survey_site_data_v3/examples/minimal.ttl
- abis_mapping/templates/survey_site_data_v3/schema.json
- abis_mapping/templates/survey_site_visit_data_v3/examples/minimal.ttl
- abis_mapping/templates/survey_site_visit_data_v3/schema.json
- abis_mapping/utils/iri_patterns.py
- tests/utils/test_iri_patterns.py
> [BDRSPS-1185] [BDRSPS-1188] [BDRSPS-1194] Various fixes to Sites' IRIs and mapping

- docs/tables/fields.py
- tests/docs/tables/test_fields.py
Site template docs:
Site visit template docs:
Occurrence template docs:
> BDRSPS-1176 Update documentation for site identifier fields

- abis_mapping/templates/survey_occurrence_data_v3/mapping.py
- tests/templates/test_survey_occurrence_data_v3.py
SSD v3: Fix occurrence mapping when using default geometry from the Site template
> BDRSPS-1193 Fix occurrence mapping when using geometry from Site template

- abis_mapping/templates/survey_site_data_v3/schema.json
This was never meant to be unique, likely a copy-paste error from existingBDRSiteIRI
> BDRSPS-1204 Remove unique constraint on relatedSiteIRI

- abis_mapping/plugins/unique_together.py
- abis_mapping/templates/survey_site_data_v3/mapping.py
- tests/plugins/test_unique_together.py
by slugifying siteIDSource before checking siteID+siteIDSource are unique for each row.
> BDRSPS-1202 Ensure site IRIs are unique for each row

- abis_mapping/utils/rdf.py
Mapping often involves slugifying the same strings repeatedly. This should be an easy performance improvement.
> BDRSPS-1212 Apply lru_cache to slugify_for_uri function

- abis_mapping/templates/survey_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v3/mapping.py
- abis_mapping/templates/survey_site_data_v3/examples/minimal.ttl
- abis_mapping/templates/survey_site_data_v3/mapping.py
- abis_mapping/templates/survey_site_visit_data_v3/examples/minimal.ttl
- abis_mapping/templates/survey_site_visit_data_v3/mapping.py
Only when the site is not an existing site.
> BDRSPS-1187 Add void:inDataset links from Site to Submission

- abis_mapping/templates/incidental_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data_v3/mapping.py
- abis_mapping/templates/survey_occurrence_data_v2/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v2/mapping.py
- abis_mapping/templates/survey_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v3/mapping.py
- abis_mapping/templates/survey_site_visit_data_v2/examples/minimal.ttl
- abis_mapping/templates/survey_site_visit_data_v3/examples/minimal.ttl
- abis_mapping/utils/iri_patterns.py
Also change recordedBy, identifiedBy, threatStatusDeterminedBy fields in occurrences to use /bdr/person/ IRIs.
> BDRSPS-1230 Update /bdr/person/ IRIs to use hashes

- abis_mapping/templates/survey_metadata_v2/metadata.json
- abis_mapping/templates/survey_metadata_v3/metadata.json
- abis_mapping/templates/survey_occurrence_data_v2/metadata.json
- abis_mapping/templates/survey_occurrence_data_v3/metadata.json
- abis_mapping/templates/survey_site_data_v2/metadata.json
- abis_mapping/templates/survey_site_data_v3/metadata.json
- abis_mapping/templates/survey_site_visit_data_v2/metadata.json
- abis_mapping/templates/survey_site_visit_data_v3/metadata.json
* SSD v2 -> deprecated
* SSD v3 -> current
> BDRSPS-1206-1207 Update template statuses

- abis_mapping/templates/incidental_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data_v3/mapping.py
- abis_mapping/templates/incidental_occurrence_data_v3/validators/validator.ttl
- abis_mapping/templates/survey_metadata_v3/examples/minimal.ttl
- abis_mapping/templates/survey_metadata_v3/mapping.py
- abis_mapping/templates/survey_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v3/mapping.py
- abis_mapping/templates/survey_occurrence_data_v3/validators/validator.ttl
- abis_mapping/templates/survey_site_data_v3/examples/minimal.ttl
- abis_mapping/templates/survey_site_data_v3/mapping.py
- abis_mapping/templates/survey_site_visit_data_v3/examples/minimal.ttl
- abis_mapping/templates/survey_site_visit_data_v3/mapping.py
Swap Collections' link to occurrences/sites/visits/surveys from `schema:member` to `schema:hasPart`
> BDRSPS-1304 Update Collections to link with `schema:hasPart`

- abis_mapping/templates/__init__.py
- abis_mapping/templates/incidental_occurrence_delete_v1/README.md
- abis_mapping/templates/incidental_occurrence_delete_v1/__init__.py
- abis_mapping/templates/incidental_occurrence_delete_v1/examples/example.csv
- abis_mapping/templates/incidental_occurrence_delete_v1/examples/example.ttl
- abis_mapping/templates/incidental_occurrence_delete_v1/incidental_occurrence_delete.csv
- abis_mapping/templates/incidental_occurrence_delete_v1/mapping.py
- abis_mapping/templates/incidental_occurrence_delete_v1/metadata.json
- abis_mapping/templates/incidental_occurrence_delete_v1/schema.json
- abis_mapping/templates/incidental_occurrence_delete_v1/templates/instructions.md
- docs/contexts/__init__.py
- docs/contexts/incidental_occurrence_delete_v1.py
- scripts/generate_instructions.sh
- tests/templates/conftest.py
- tests/templates/test_common.py
Still to do in follow up PRs:
* Add mapping - waiting for specification
* Maybe add more to instructions doc
> BDRSPS-1263 Add Incidental Occurrence delete template v1

- abis_mapping/base/mapper.py
- tests/templates/test_mapping.py
Try to garbage collect each chunk graph before generating the next one, to reduce peak memory usage.
> BDRSS-636 Try to reduce graph memory usage

- abis_mapping/templates/incidental_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data_v3/mapping.py
- abis_mapping/templates/survey_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v3/mapping.py
- abis_mapping/utils/iri_patterns.py
Map the value of this field to a `tern:Result` instead of a `tern:Sample`
> BDRSPS-1376 Update mapping for `associatedSequences` field

- pyproject.toml
> BDRSPS-1340: v8.0.0-rc1

- abis_mapping/templates/incidental_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_metadata_v3/examples/minimal.ttl
- abis_mapping/templates/survey_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v3/examples/organism_qty.ttl
- abis_mapping/templates/survey_site_data_v3/examples/minimal.ttl
- abis_mapping/templates/survey_site_visit_data_v3/examples/minimal.ttl
- abis_mapping/utils/iri_patterns.py
- abis_mapping/utils/namespaces.py
Remove the `/dataset/bdr` part from Org IRIs,
so they look like `https://linked.data.gov.au/org/<org-name>`
> BDRSPS-1381 Change Org agent IRIs

- abis_mapping/templates/incidental_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data_v3/mapping.py
- abis_mapping/templates/survey_metadata_v3/examples/minimal.ttl
- abis_mapping/templates/survey_metadata_v3/mapping.py
- abis_mapping/templates/survey_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v3/examples/organism_qty.ttl
- abis_mapping/templates/survey_occurrence_data_v3/mapping.py
- abis_mapping/templates/survey_site_visit_data_v3/examples/minimal.ttl
- abis_mapping/templates/survey_site_visit_data_v3/mapping.py
Swap time:hasTime for schema:temporal as the predicate for time:Instant and time:TemporalEntity
> BDRSPS-1417 Swap time:hasTime for schema:temporal 

- pyproject.toml
bump version to v8.0.0-rc2 for release
> BDRSPS-1390: v8.0.0-rc2

- abis_mapping/templates/incidental_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/incidental_occurrence_data_v3/mapping.py
- abis_mapping/templates/survey_occurrence_data_v3/examples/margaret_river_flora/margaret_river_flora.ttl
- abis_mapping/templates/survey_occurrence_data_v3/examples/organism_qty.ttl
- abis_mapping/templates/survey_occurrence_data_v3/mapping.py
> BDRSPS-1468 Swap human observation for unspecified method on Observation nodes
